export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  USER_ID_REQUIRED: 'USER_ID_REQUIRED',
  INVALID_USER_ID: 'INVALID_USER_ID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  OPERATOR_ACCESS_REQUIRED: 'OPERATOR_ACCESS_REQUIRED',

  CONCERT_NOT_FOUND: 'CONCERT_NOT_FOUND',
  CONCERT_NOT_PUBLISHED: 'CONCERT_NOT_PUBLISHED',
  CONCERT_ALREADY_PUBLISHED: 'CONCERT_ALREADY_PUBLISHED',
  CONCERT_NOT_PUBLISHABLE: 'CONCERT_NOT_PUBLISHABLE',

  TICKET_CATEGORY_NOT_FOUND: 'TICKET_CATEGORY_NOT_FOUND',
  TICKET_CATEGORY_NOT_IN_CONCERT: 'TICKET_CATEGORY_NOT_IN_CONCERT',
  TICKET_CATEGORY_ALREADY_EXISTS: 'TICKET_CATEGORY_ALREADY_EXISTS',
  INSUFFICIENT_TICKET_INVENTORY: 'INSUFFICIENT_TICKET_INVENTORY',

  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  INVALID_BOOKING_STATUS_TRANSITION:
    'INVALID_BOOKING_STATUS_TRANSITION',

  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',
  VOUCHER_INACTIVE: 'VOUCHER_INACTIVE',
  VOUCHER_NOT_STARTED: 'VOUCHER_NOT_STARTED',
  VOUCHER_EXPIRED: 'VOUCHER_EXPIRED',
  VOUCHER_USAGE_LIMIT_REACHED: 'VOUCHER_USAGE_LIMIT_REACHED',
  VOUCHER_ALREADY_USED: 'VOUCHER_ALREADY_USED',
  VOUCHER_CODE_ALREADY_EXISTS: 'VOUCHER_CODE_ALREADY_EXISTS',

  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  

  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  TRANSACTION_RETRY_EXHAUSTED: 'TRANSACTION_RETRY_EXHAUSTED',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode =
  (typeof ErrorCode)[keyof typeof ErrorCode];